/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import edu.gatech.oad.antlab.person.Person3;


public class Person3Tester {
    private Person3 a = new Person3("abcd");
    private Person3 b = new Person3("123456");
    @Test
    public void toStringTester() {
        assertEquals("abcd", a.toString("dcba"));
        assertEquals("123456", b.toString("654321"));
    }

    @Test()
    public void nullPointerTester() {
        String in = a.toString(null);
        String out = b.toString(null);
    }
}
