/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.*;

import edu.gatech.oad.antlab.person.Person3;
import org.junit.Test;

public class Person3Tester {
  private Person3 a = new Person3("Waters");

  @Test
  public void toStringTester() {
    assertEquals("Waterscba", a.toString("abc"));
    assertEquals("Waters123456", a.toString("654321"));
  }

  @Test(expected = IllegalArgumentException.class)
  public void nullPointerTester() {
    String in = a.toString(null);
  }
}
